# Generated by Django 5.2 on 2025-05-11 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=1)),
                ('name', models.CharField(max_length=40)),
                ('parents_name', models.CharField(max_length=40)),
                ('address', models.CharField(blank=True, default='', max_length=40)),
                ('phone_no', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(null=True, upload_to='students/')),
                ('grade', models.CharField(blank=True, default='', max_length=10)),
                ('prev_school', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('Reg_no', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('designation', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=80)),
                ('phone_no', models.CharField(max_length=12)),
                ('photo', models.ImageField(null=True, upload_to='volunteer/')),
                ('interest', models.CharField(blank=True, default='', max_length=40)),
                ('experience', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('math', models.CharField(blank=True, max_length=60, null=True)),
                ('hindi', models.CharField(blank=True, max_length=60, null=True)),
                ('english', models.CharField(blank=True, max_length=60, null=True)),
                ('extra_curricular', models.CharField(blank=True, max_length=60, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_repost', to='dashboard.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='dashboard.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
