# Generated by Django 5.2 on 2025-05-28 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_progress_updated_by_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignedTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_given_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
