# Generated by Django 5.2 on 2025-10-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_volunteer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.PositiveSmallIntegerField(choices=[(1, 'Monday (10:00–11:40)'), (2, 'Monday (11:40–12:30)'), (3, 'Tuesday (10:00–11:40)'), (4, 'Tuesday (11:40–12:30)'), (5, 'Wednesday (10:00–11:40)'), (6, 'Wednesday (11:40–12:30)'), (7, 'Thursday (10:00–11:40)'), (8, 'Thursday (11:40–12:30)'), (9, 'Friday (10:00–11:40)'), (10, 'Friday (11:40–12:30')], unique=True)),
            ],
            options={
                'ordering': ['slot_id'],
            },
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='slots',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='dashboard.slot'),
        ),
    ]
