# Generated by Django 5.2 on 2025-10-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_slot_alter_volunteer_status_volunteer_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='designation',
            field=models.CharField(default='Teacher', max_length=25),
        ),
    ]
